/**
 * code generated by JHelper
 * More info: https://github.com/AlexeyDmitriev/JHelper
 * @author tatsumack
 */

#include <iostream>
#include <fstream>

#include <iostream>
#include <limits.h>
#include <algorithm>
#include <bitset>
#include <cctype>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <deque>
#include <functional>
#include <iomanip>

#include <list>
#include <map>
#include <numeric>
#include <set>
#include <sstream>
#include <stack>
#include <string>
#include <utility>
#include <vector>
#include <queue>
#include <unordered_map>
#include <unordered_set>

#define int long long
#define REP(i, n) for (int i = 0, i##_len = (n); i < i##_len; ++i)
#define REPS(i, n) for (int i = 1, i##_len = (n); i <= i##_len; ++i)
#define FOR(i, a, b) for (int i = (a), i##_len = (b); i <= i##_len; ++i)
#define REV(i, a, b) for (int i = (a); i >= (b); --i)
#define CLR(a, b) memset((a), (b), sizeof(a))
#define DUMP(x) cout << #x << " = " << (x) << endl;
#define INF 1001001001001001001ll
#define fcout cout << fixed << setprecision(12)

using namespace std;

template<typename T>
vector<T> make_v(size_t a) { return vector<T>(a); }

template<typename T, typename... Ts>
auto make_v(size_t a, Ts... ts) {
    return vector<decltype(make_v<T>(ts...))>(a, make_v<T>(ts...));
}

template<typename T, typename V>
typename enable_if<is_class<T>::value == 0>::type
fill_v(T& t, const V& v) { t = v; }

template<typename T, typename V>
typename enable_if<is_class<T>::value != 0>::type
fill_v(T& t, const V& v) {
    for (auto& e:t) fill_v(e, v);
}

typedef pair<int, int> P;

class CComeTogether {
public:
    void solve(std::istream& cin, std::ostream& cout) {
        int H, W, K;
        cin >> H >> W >> K;
        vector<int> vh(H, W), vw(W, H);
        REP(i, K) {
            int r, c;
            cin >> r >> c;
            r--, c--;
            vh[r]--;
            vw[c]--;
        }

        vector<int> sumh(H + 1), sumw(W + 1);
        REP(i, H) {
            sumh[i+1] = sumh[i] + vh[i];
        }
        REP(i, W) {
            sumw[i+1] = sumw[i] + vw[i];
        }

        int n = (H * W - K + 1) / 2;
        int th = -1;
        REP(i, H) {
            if (sumh[i + 1] >= n) {
                th = i;
                break;
            }
        }
        int tw = -1;
        REP(i, W) {
            if (sumw[i + 1] >= n) {
                tw = i;
                break;
            }
        }
        int res = 0;
        REP(i, H) {
            res += abs(th - i) * vh[i];
        }
        REP(i, W) {
            res += abs(tw - i) * vw[i];
        }
        cout << res << endl;

    }
};


signed main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);
    cout.tie(nullptr);
    std::istream& in(std::cin);
    std::ostream& out(std::cout);

    CComeTogether solver;
    solver.solve(in, out);
    return 0;
}
